# Generated by Django 2.0.4 on 2018-09-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='Fecha')),
                ('todo', models.CharField(max_length=150, verbose_name='Que hay que hacer?')),
                ('errase', models.BooleanField()),
                ('archive', models.BooleanField()),
            ],
        ),
    ]
