# Generated by Django 2.0.4 on 2018-09-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODOapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='archive',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='task',
            name='errase',
            field=models.BooleanField(default=None),
        ),
    ]
