# Generated by Django 2.0.4 on 2018-09-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODOapp', '0002_auto_20180907_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='errase',
        ),
        migrations.AlterField(
            model_name='task',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
